baseURL = 'https://cr-jb.codefighters.net/'
languageCode = 'en-us'
title = 'Coder Radio'

theme = 'jb'

# directory where the output is generated to
publishdir = 'public_coderradio'

# Allow HTML in Markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"
  host = "hosts"
  guest = "guests"

# Main Menu
[[Menu.Main]]
    name = "Coder Radio"
    identifier = "home"
    url = "/"
    weight =-100

[[Menu.Main]]
    name = "Episodes"
    identifier = "episodes"
    url = "/episodes"
    weight =-90

contentDir = "sites/coderradio/content"
# Module mounts
[module]
#[[module.mounts]]
#  source = 'sites/coderradio/content'
#  target = 'content'
# currently it prevents us from mounting sites/coderradio/content directly
# https://github.com/gohugoio/hugo/issues/7123
[[module.mounts]]
  source = 'sites/coderradio/content/community'
  target = 'content/community'
[[module.mounts]]
  source = 'content/show/coderradio'
  target = 'content/episodes'
[[module.mounts]]
  source = 'static'
  target = 'static'
[[module.mounts]]
  source = 'layouts'
  target = 'layouts'
[[module.mounts]]
  source = 'data'
  target = 'data'
[[module.mounts]]
  source = 'assets'
  target = 'assets'
[[module.mounts]]
  source = 'i18n'
  target = 'i18n'
[[module.mounts]]
  source = 'archetypes'
  target = 'archetypes'
