baseURL = 'https://jb.codefighters.net/'
languageCode = 'en-us'
title = 'Jupiter Broadcasting'

theme = 'jb'

# Allow HTML in Markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "hosts"
