baseURL = 'https://jb.codefighters.net/'
languageCode = 'en-us'
title = 'Jupiter Broadcasting'

theme = 'jb'

# Allow HTML in Markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Meta Data
[params]
  keywords = "Linux, FreeBSD, howto, Ubuntu, Arch, tech news, HD, app review, Systems, Network, Sysadmin, netsec, Politics, development, podcast, Linux Action Show, TechSNAP, SciByte, FauxShow, Coder Radio, LIVE stream, Bitcoin, PlanB, BSDNow"
  description = "Independent coverage of Linux, BSD, Open Source, System Administration, Information Security, News, Software Development and Discussion."
  author = "Jupiter Broadcasting"
  ogimage = "/images/jupiter-broadcasting.png" # Open Graph default image
