version: '3'
services:
  jbsite:
    image: jbsite
    container_name: jbsite
    restart: unless-stopped
    build:
      context: .
    ports:
      - 1111:80
  fireside-scraper:
    user: 1000:1000
    image: fireside-scraper
    container_name: fireside-scraper
    environment:
      - DATA_ROOT_DIR=/data
      - HUGO_DATA_DIR=/hugo-data
    build:
      context: ./fireside-scraper
    volumes:
      - ./scraped-data:/data
      - ./data:/hugo-data:ro
